services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    restart: always
  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
    depends_on:
      - app